image: barichello/godot-ci:3.2.3

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - godot_project/.import/

stages:
  - export

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  EXPORT_NAME: where-wolf

windows_dev:
  stage: export
  script:
    - mkdir -v -p build/windows_dev
    - cd godot_project
    - godot -v --export-debug "Windows Desktop Dev" ../build/windows_dev/$EXPORT_NAME.exe
    - godot -s ./CopyAssetFolders.gd "--build-path build/windows_dev"
    - test -e ../build/windows_dev/$EXPORT_NAME.exe
    - test -e ../build/windows_dev/default_options.cfg
    - test -e ../build/windows_dev/default_controls.json
    - test -e ../build/windows_dev/default_context.json
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows_dev
  only:
      - master

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - cd godot_project
    - godot -v --export-debug "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
    - test -e ../build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows
  only:
      - master