extends Node

# Input
enum CONTROL_SCHEME {  HYBRID = 0, MOUSE = 1, KEYBOARD = 2 }

# Movement
enum DIRECTION { E, SE, S, SW, W, NW, N, NE }
enum WALK_MODE { WALKING, RUNNING }

# Sound
enum SOUND_REGION { DEFAULT, FLOOR, CARPET, WHEAT }
enum SOUND_SOURCE_TYPE { NONE, INTERACTION, SABOTAGING, BREAKING, WALKING, ATTACKED }


enum WAYPOINT_REGION{ DEFAULT, OVEN, TABLE, SINK, WHEAT, FOREST, WOODPLACE }
